# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: giseldo.NeoChat
PackageVersion: 0.0.8
InstallerType: nullsoft
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
ReleaseDate: 2026-09-17
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/giseldo/neochat-desktop/releases/download/v0.0.8/NeoChat-Desktop-Setup.exe
    InstallerSha256: 97551E3DF992CB9EB5F2C22DD1F9AD1909D74C44D8266D9988607DA372954F18
ManifestType: installer
ManifestVersion: 1.6.0
