export const PROVIDERS = {
  groq: {
    id: 'groq',
    name: 'Groq',
    description: 'Inferência ultra-rápida via LPUs da Groq.',
    baseUrl: 'https://api.groq.com/openai/v1',
    models: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile', context: 128000 },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant', context: 128000 },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B', context: 32768 },
      { id: 'gemma2-9b-it', name: 'Gemma 2 9B IT', context: 8192 },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill 70B', context: 128000 },
    ],
    defaultModel: 'llama-3.3-70b-versatile',
    keyPlaceholder: 'gsk_...',
    keyUrl: 'https://console.groq.com/keys',
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    description: 'Modelos GPT-4o, GPT-4o-mini e reasoning o1/o3-mini.',
    baseUrl: 'https://api.openai.com/v1',
    models: [
      { id: 'gpt-4o', name: 'GPT-4o', context: 128000 },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', context: 128000 },
      { id: 'o3-mini', name: 'o3-mini', context: 200000 },
      { id: 'o1', name: 'o1', context: 200000 },
    ],
    defaultModel: 'gpt-4o-mini',
    keyPlaceholder: 'sk-proj-...',
    keyUrl: 'https://platform.openai.com/api-keys',
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    description: 'Claude 3.7 Sonnet, Claude 3.5 Sonnet & Haiku.',
    baseUrl: 'https://api.anthropic.com/v1',
    models: [
      { id: 'claude-3-7-sonnet-20250219', name: 'Claude 3.7 Sonnet (Hybrid)', context: 200000 },
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet v2', context: 200000 },
      { id: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku', context: 200000 },
    ],
    defaultModel: 'claude-3-5-sonnet-20241022',
    keyPlaceholder: 'sk-ant-...',
    keyUrl: 'https://console.anthropic.com/settings/keys',
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Modelos Gemini 2.0 Flash e 1.5 Pro.',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    models: [
      { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', context: 1048576 },
      { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro', context: 2097152 },
      { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', context: 1048576 },
    ],
    defaultModel: 'gemini-2.0-flash',
    keyPlaceholder: 'AIzaSy...',
    keyUrl: 'https://aistudio.google.com/app/apikey',
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek-V3 e DeepSeek-R1 via API direta.',
    baseUrl: 'https://api.deepseek.com/v1',
    models: [
      { id: 'deepseek-chat', name: 'DeepSeek V3 (Chat)', context: 64000 },
      { id: 'deepseek-reasoner', name: 'DeepSeek R1 (Reasoner)', context: 64000 },
    ],
    defaultModel: 'deepseek-chat',
    keyPlaceholder: 'sk-...',
    keyUrl: 'https://platform.deepseek.com/api_keys',
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral Large, Pixtral, Codestral e Mistral NeMo.',
    baseUrl: 'https://api.mistral.ai/v1',
    models: [
      { id: 'mistral-large-latest', name: 'Mistral Large', context: 128000 },
      { id: 'codestral-latest', name: 'Codestral', context: 256000 },
      { id: 'open-mistral-nemo', name: 'Mistral NeMo', context: 128000 },
    ],
    defaultModel: 'mistral-large-latest',
    keyPlaceholder: '...',
    keyUrl: 'https://console.mistral.ai/api-keys/',
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Acesso a mais de 200 modelos de IA em um único endpoint.',
    baseUrl: 'https://openrouter.ai/api/v1',
    models: [
      { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B (OpenRouter)', context: 131072 },
      { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet', context: 200000 },
      { id: 'openai/gpt-4o', name: 'GPT-4o', context: 128000 },
      { id: 'deepseek/deepseek-r1', name: 'DeepSeek R1', context: 64000 },
    ],
    defaultModel: 'meta-llama/llama-3.3-70b-instruct',
    keyPlaceholder: 'sk-or-...',
    keyUrl: 'https://openrouter.ai/keys',
  },
};

export const DEFAULT_PROVIDER = 'groq';
export const DEFAULT_MODEL = 'llama-3.3-70b-versatile';
