name: Publish to WinGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Submit to WinGet
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: giseldo.NeoChat
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
